export { parseAssetToml, parseProjectToml } from "./toml.js";
export {
  SOURCE_MAP_DIGEST_BASIS,
  SOURCE_MAP_FILENAME,
  SOURCE_MAP_SCHEMA_VERSION,
  computeSourceMapDigest,
  parseSourceMap,
  serializeSourceMap,
  type SourceIdentityStrategy,
  type SourceMapCollectionV1,
  type SourceMapEntryV1,
  type SourceMapExclusionV1,
  type SourceMapOverrideV1,
  type SourceMapV1,
} from "./source-map.js";
export {
  PORTABLE_COMPONENT_MAX_BYTES,
  PORTABLE_PATH_MAX_BYTES,
  SOURCE_MAP_ID_MAX_BYTES,
  deriveSourceMapId,
  deriveSourceMapIdCandidate,
  deriveSourceMapIdentities,
  evaluateSourceMapSelection,
  portablePathKey,
  validatePortablePath,
  type PortablePathOptions,
  type SourceIdentity,
  type SourceIdentityCandidate,
  type SourceSelection,
  type SourceSelectionCandidate,
} from "./source-identity.js";
export {
  WORKSPACE_DIGEST_BASIS,
  WORKSPACE_FILENAME,
  WORKSPACE_MAX_BYTES,
  WORKSPACE_MAX_PROJECTS,
  WORKSPACE_SCHEMA_VERSION,
  computeWorkspaceDigest,
  discoverWorkspace,
  parseWorkspace,
  serializeWorkspace,
  type DiscoveredWorkspaceProject,
  type WorkspaceDiscoveryResult,
  type WorkspaceProjectV1,
  type WorkspaceV1,
  type WorkspaceStreamMetrics,
} from "./workspace.js";
export {
  DEFAULT_WORKSPACE_PAGE_SIZE,
  MAX_WORKSPACE_PAGE_SIZE,
  WORKSPACE_LIST_CURSOR_BASIS,
  WORKSPACE_LIST_CURSOR_SCHEMA_VERSION,
  WORKSPACE_LIST_VIEW_BASIS,
  listWorkspace,
  createWorkspaceListCursor,
  parseWorkspaceListCursor,
  serializeWorkspaceListCursor,
  type WorkspaceListCursorV1,
  type WorkspaceListOptions,
  type WorkspaceListRecord,
  type WorkspaceListResult,
  type WorkspaceListHooks,
  type WorkspaceRecordKey,
} from "./workspace-list.js";
export { checkWorkspace, type WorkspaceCheckOptions, type WorkspaceCheckResult, type WorkspaceChildCheckSummary } from "./workspace-check.js";
export {
  DEFAULT_WORKSPACE_PREVIEW_OUTPUT,
  WORKSPACE_PREVIEW_MARKER_FILENAME,
  WORKSPACE_PREVIEW_MARKER_KIND,
  WORKSPACE_PREVIEW_PAGE_SIZE,
  WORKSPACE_PREVIEW_TREE_BASIS,
  WORKSPACE_PREVIEW_VIEW_BASIS,
  parseWorkspacePreviewMarker,
  previewWorkspace,
  serializeWorkspacePreviewMarker,
  type WorkspacePreviewMarker,
  type WorkspacePreviewMetrics,
  type WorkspacePreviewOptions,
  type WorkspacePreviewResult,
} from "./workspace-preview.js";
export {
  DIRECTORY_FILE_BYTES_BASIS,
  DIRECTORY_SNAPSHOT_BASIS,
  DIRECTORY_SNAPSHOT_UNSUPPORTED,
  closeDirectorySnapshot,
  computeDirectorySnapshotDigest,
  createDirectorySnapshot,
  discoverDirectorySources,
  getDirectorySnapshotCapability,
  qualifyDirectorySnapshotPlatform,
  revalidateDirectorySnapshot,
  revalidateDirectoryDiscovery,
  type AuthenticatedDirectoryRevalidationResult,
  type AuthenticatedDirectorySnapshot,
  type DirectoryChildDto,
  type DirectoryCompanionDto,
  type DirectoryDiscoveryResult,
  type DirectoryDiscoveryOptions,
  type DirectoryFileDto,
  type DirectoryInventoryDto,
  type DirectoryRevalidationResult,
  type DirectorySnapshotCapability,
  type DirectorySnapshotQualification,
  type DirectorySnapshotSelectionOptions,
  type SupportedDirectorySnapshotCapability,
  type UnsupportedDirectorySnapshotCapability,
} from "./directory-snapshot.js";
export { analyze, createAnalyzeEnvelope, executeCompleteAnalysis, mapAnalyzeJson, renderAnalyzeHuman, type AnalyzeEnvelope, type AnalyzeOptions } from "./analyze.js";
export { planAnalyzeDetails, publishAnalyzeDetails, serializeAnalyzeDetails, serializeAnalyzeDetailsLines, type AnalyzeDetailsHooks, type AnalyzeDetailsPlan, type AnalyzeDetailsPublicationResult } from "./analyze-details.js";
export { deriveAnalyzeAssetId, inspectAnalyzeInput, verifyAnalyzeInputPlan, type AnalyzeInputPlan, type AnalyzeSourceHooks } from "./analyze-source.js";
export { ANALYZE_COMMON_V03_PROFILE, ANALYZE_DIAGNOSTIC_REGISTRY, ANALYZE_FEATURE_CODE_REGISTRY, ANALYZE_LIMITS, ANALYZE_NORMALIZATION_REGISTRY, ANALYZE_SCHEMA1_PROFILE, analyzeDiagnosticSpec, analyzeMessage, type AnalyzeCode, type AnalyzeCounts, type AnalyzeDetailsFile, type AnalyzeDetailsFooter, type AnalyzeDetailsHeader, type AnalyzeDetailsLocation, type AnalyzeDetailsProfile, type AnalyzeDiagnosticDomain, type AnalyzeFeatureCode, type AnalyzeIdentitySummary, type AnalyzeInputKind, type AnalyzeJsonData, type AnalyzeNormalization, type AnalyzeProfileAggregate, type AnalyzeProfileKey, type AnalyzeResult, type CommonV03Classification, type Schema1Classification } from "./analyze-contract.js";
export { TOOL_VERSION } from "./version.js";
export { serializeAssetToml, serializeProjectToml } from "./toml-writer.js";
export { parseSvg, serializeSvg } from "./svg.js";
export { parseAssetTomlV2, parseProjectTomlV2, serializeAssetTomlV2, serializeProjectTomlV2 } from "./schema2-toml.js";
export { parseSvgV2, serializeSvgV2 } from "./schema2-svg.js";
export { disposeImportPlan, executeImport, importProject, planImport, type ImportOptions, type ImportPlan, type ImportSource, type SelectedDirectoryCompanion } from "./importer.js";
export { ASSET_DIGEST_BASIS, ASSET_DIGEST_BASIS_V2, PATH_DIGEST_BASIS, SVG_OUTPUT_DIGEST_BASIS, computeAssetSemanticDigest, computeCompanionByteDigest, computePathTextDigest, computeRawSha256, computeSha256, computeSvgOutputDigest } from "./digests.js";
export { NORMALIZATION_MAP_SCHEMA_VERSION, normalizationAuthorityFor, parseNormalizationMap, serializeNormalizationMap, unwrapNormalizationMap, type NormalizationMapEntryV1, type NormalizationMapV1, type UnlabelledAccessibilityAuthority } from "./normalization-map.js";
export { NORMALIZATION_POLICY_BASIS, NORMALIZATION_POLICY_ID, NORMALIZATION_POLICY_VERSION, NORMALIZATION_TARGET_SCHEMA_VERSION, computeNormalizationMapSha256, computeNormalizationPolicyDigest, createNormalizationPolicyIdentity, normalizationPolicyBytes, normalizationPolicyMatches, type MapSha256, type NormalizationPolicyIdentityV1 } from "./normalization-policy.js";
export { NORMALIZATION_LEDGER_SCHEMA_VERSION, type NormalizationDisposition, type NormalizationLedgerEntryV1, type NormalizationLedgerV1, type NormalizationOperationCode } from "./normalization-ledger.js";
export { normalizeCommonSvg, type NormalizeSvgOptions, type NormalizedSvgResult } from "./normalizer.js";
export { executeMigration, migrateAssetModel, migrateProject, planMigration, type MigrationFilePlan, type MigrationOptions, type MigrationPlan, type MigrationResult } from "./migration.js";
export { executeAssetEdit, planAssetEdit, type AssetEditOptions, type AssetEditPlan } from "./edit.js";
export {
  BUILD_RECEIPT_FILENAME,
  createBuildReceipt,
  parseBuildReceipt,
  readBuildReceipt,
  receiptOwnsProject,
  serializeBuildReceipt,
  type BuildReceipt,
  type BuildReceiptV2,
  type BuildReceiptV3,
  type BuildReceiptReadResult,
  type BuildReceiptProjectPolicyV3,
} from "./receipt.js";
export { parseImportProvenance, serializeImportProvenance } from "./provenance.js";
export { ARCHIVE_DIGEST_BASIS, ARCHIVE_SOURCE_DIGEST_BASIS, COMPANION_DIGEST_BASIS, MIGRATION_RESOLUTION, PROVENANCE_SCHEMA_VERSION_V2, parseImportProvenanceV2, serializeImportProvenanceV2, unwrapProvenanceV2, type ArchiveCheckpointV2, type AssetProvenanceRecordV2, type CompanionProvenanceRecordV2, type ImportProvenanceV2, type MigrationEvidenceV2, type ProvenanceRecordV2 } from "./provenance2.js";
export { PROVENANCE_SCHEMA_VERSION_V3, liftImportProvenanceV2ToV3, parseImportProvenanceV3, serializeImportProvenanceV3, unwrapProvenanceV3, type ArchiveSourceCheckpointV3, type AssetProvenanceRecordV3, type CompanionProvenanceRecordV3, type DirectorySourceCheckpointV3, type ImportProvenanceV3, type ProvenanceRecordV3, type ProvenanceSourceCheckpointV3 } from "./provenance3.js";
export {
  BUNDLE_MANIFEST_FILENAME,
  BUNDLE_MANIFEST_KIND,
  BUNDLE_MANIFEST_SCHEMA_VERSION,
  BUNDLE_MANIFEST_SCHEMA_VERSION_V2,
  BUNDLE_MANIFEST_MAX_ENTRIES_V2,
  parseBundleManifest,
  parseBundleManifestV2,
  serializeBundleManifest,
  serializeBundleManifestV2,
  serializeBundleManifestVersioned,
  unwrapBundleManifest,
  validatePortablePathV2,
  type AnyBundleManifest,
  type BundleManifestAssetRecord,
  type BundleManifestAssetRecordV2,
  type BundleManifestCompanionRecord,
  type BundleManifestCompanionRecordV2,
  type BundleManifestFileRecord,
  type BundleManifestFileRecordV2,
  type BundleManifestGenerator,
  type BundleManifestRecordV2,
  type BundleManifestV1,
  type BundleManifestV2,
} from "./manifest.js";
export {
  bundleProject,
  executeBundle,
  planBundle,
  type BundleEntryDto,
  type BundleOptions,
  type BundlePlan,
  type BundleResult,
} from "./bundle.js";
export {
  readManifestArchive,
  type ManifestArchiveAssetEntry,
  type ManifestArchiveCompanionEntry,
  type ManifestArchiveReadResult,
} from "./archive.js";
export { classifyAssetRecord, classifyCompanionRecord, classifyPairedCheckpoint } from "./classifier.js";
export {
  MAX_LIFECYCLE_ASSETS,
  enforceMutationAssetLimit,
  loadCanonicalProject,
  loadCanonicalProjectFromSnapshot,
  verifyLoadedProjectSnapshot,
  type LoadedProject,
} from "./project.js";
export { executeReconciliationPlan, planReconciliation, reconcileProject } from "./reconcile.js";
export { buildProject, executeBuild, planBuild, type BuildPlan, type BuildPlanOutput } from "./build.js";
export { executeInstall, installProject, planInstall, type InstallPlan, type InstallPlanItem } from "./install.js";
export { checkProject } from "./check.js";
export { listProject } from "./list.js";
export {
  diffArchive,
  diffBuild,
  diffInstall,
  diffProject,
  diffProvenance,
  type ArchiveDiffResult,
  type ArchiveSourceRelation,
  type ArchiveSemanticChange,
  type BuildDiffResult,
  type DiffBaseline,
  type DiffOptions,
  type DiffResult,
  type InstallDiffResult,
  type PathTextChange,
  type ProvenanceDiffResult,
} from "./diff.js";
export { executeFormat, formatProject, planFormat, type FormatOptions, type FormatPlan, type FormatResult } from "./fmt.js";
export {
  DEFAULT_PREVIEW_OUTPUT,
  PREVIEW_MARKER_FILENAME,
  PREVIEW_MARKER_KIND,
  executePreviewPlan,
  parsePreviewMarker,
  planPreview,
  previewProject,
  serializePreviewMarker,
  type PreviewAssetResult,
  type PreviewBuildStatus,
  type PreviewCompanionResult,
  type PreviewDestinationState,
  type PreviewDestinationStatus,
  type PreviewFilesResult,
  type PreviewGeometryProfile,
  type PreviewInstallStatus,
  type PreviewMarker,
  type PreviewMarkerReadResult,
  type PreviewOpenResult,
  type PreviewOpener,
  type PreviewOptions,
  type PreviewPlan,
  type PreviewResult,
  type PreviewTransactionHooks,
} from "./preview.js";
export {
  JSON_RESULT_SCHEMA_VERSION,
  createJsonEnvelope,
  mapCheckJson,
  mapListJson,
  mapMachineDiagnostic,
  mapReconcileJson,
  serializeJsonEnvelope,
  type BundleJsonData,
  type ImportJsonData,
  type CheckJsonData,
  type DiffJsonData,
  type FormatJsonData,
  type JsonCommand,
  type JsonResultEnvelope,
  type ListJsonData,
  type MachineDiagnostic,
  type PreviewJsonData,
  type ReconcileJsonData,
  type ShardJsonData,
  type WorkspaceCheckJsonData,
  type WorkspaceListJsonData,
  type WorkspacePreviewJsonData,
} from "./json.js";
export type {
  Accessibility,
  ArtworkElement,
  Canvas,
  CompanionDeclaration,
  Definitions,
  DefinitionPath,
  Diagnostic,
  DiagnosticDomain,
  DiagnosticOperation,
  GradientStop,
  InstallDeclaration,
  LinearGradient,
  NormalizedAsset,
  NormalizedProject,
  Paint,
  PathSpec,
  Presentation,
  Result,
  SvgDocument,
  TransformOperation,
  UseSpec,
} from "./types.js";
export type {
  AccessibilityV2,
  ArtworkElementV2,
  DefinitionsV2,
  ElementPresentationV2,
  NormalizedAssetV2,
  NormalizedProjectV2,
  PaintV2,
  PresentationV2,
  SvgDocumentV2,
  TransformOperationV2,
} from "./schema2-types.js";
export type {
  AssetProvenanceRecordV1,
  CompanionProvenanceRecordV1,
  ImportProvenanceV1,
  ProvenanceRecordV1,
} from "./provenance.js";
export type {
  PairedCheckpointClassification,
  PairedCheckpointInput,
  RecordedCheckpoint,
} from "./classifier.js";
export type {
  ReconcileOptions,
  ReconciliationClassification,
  ReconciliationPlan,
  ReconciliationRecord,
  ReconciliationResult,
  ReconcilePlannedAction,
  ReconcileRequiredAuthority,
} from "./reconcile.js";
export {
  disposeDirectoryReconciliationPlan,
  executeDirectoryReconcilePlan,
  executeDirectoryReconciliationPlan,
  planDirectoryReconcile,
  planDirectoryReconciliation,
  reconcileDirectory,
  reconcileDirectoryProject,
  type DirectoryReconciliationClassification,
  type DirectoryReconciliationOptions,
  type DirectoryReconciliationPlan,
  type DirectoryReconciliationPlannedAction,
  type DirectoryReconciliationRecord,
  type DirectoryReconciliationRequiredAuthority,
  type DirectoryReconciliationResult,
} from "./reconcile-directory.js";
export {
  SHARD_MANIFEST_MAX_BYTES,
  SHARD_MANIFEST_SCHEMA_VERSION,
  SHARD_MEMBERSHIP_BASIS,
  SHARD_PROFILE,
  computeShardMembershipDigest,
  disposeShardManifestOutputPlan,
  parseShardManifest,
  planShard,
  planShardManifest,
  planShardManifestOutput,
  publishShardManifest,
  serializeShardManifest,
  type ShardAssetV1,
  type ShardManifestOutputPlan,
  type ShardManifestPublicationResult,
  type ShardManifestV1,
  type ShardPlanningOptions,
} from "./shard.js";
export {
  BRAND_BUILTIN_ROLES,
  BRAND_DIGEST_BASIS,
  BRAND_FILE_INVENTORY,
  BRAND_SCHEMA_ID,
  BRAND_SCHEMA_VERSION,
  BRAND_SYSTEM_DIGEST_BASIS,
  BRAND_TOML_MAX_BYTES,
  OPTIONAL_BRAND_DOMAINS,
  getFixedBrandFile,
  isFixedBrandFilePath,
  type BrandBuiltinRole,
  type BrandDomain,
  type BrandFileEntry,
  type BrandOptionalDomain,
} from "./brand/brand-files.js";
export {
  BRAND_AUTHORITIES,
  BRAND_BACKGROUNDS,
  BRAND_COLOR_MODES,
  BRAND_MAX_BINDINGS,
  BRAND_MAX_BINDINGS_PER_ASSET,
  BRAND_MAX_DIMENSION_PX,
  BRAND_MAX_DISPLAY_ORDER,
  BRAND_MAX_FAMILIES,
  BRAND_MAX_HUMAN_NAME_BYTES,
  BRAND_MAX_REFERENCED_ASSETS,
  BRAND_MAX_REQUIREMENTS,
  BRAND_MAX_ROLES,
  BRAND_MAX_VARIANTS,
  BRAND_MIN_DIMENSION_PX,
  BRAND_MIN_DISPLAY_ORDER,
  BRAND_SCALES,
  BRAND_VARIANT_STATUSES,
  isValidBrandRole,
  parseBrandToml,
  serializeBrandToml,
  type BrandAuthority,
  type BrandBackground,
  type BrandBinding,
  type BrandColorMode,
  type BrandEnabledDomains,
  type BrandFamily,
  type BrandModel,
  type BrandRequirement,
  type BrandScale,
  type BrandVariant,
  type BrandVariantStatus,
} from "./brand/brand-schema.js";
export {
  computeBrandDigest,
  computeBrandSystemDigest,
  encodeCanonicalJson,
  type BrandSystemDigestInput,
} from "./brand/brand-digests.js";
export {
  type BrandDomainAvailability,
  type BrandDomainState,
} from "./brand/brand-availability.js";
export {
  validateBrandSemantics,
} from "./brand/brand-core.js";
export {
  BRAND_PACKAGE_COMPANION_PURPOSES,
  BRAND_PACKAGE_DIGEST_BASIS,
  BRAND_PACKAGE_MAX_BYTES,
  BRAND_PACKAGE_MAX_COMPANIONS,
  BRAND_PACKAGE_MAX_ENTRIES,
  BRAND_PACKAGE_MAX_FAMILIES,
  BRAND_PACKAGE_MAX_INVENTORY,
  BRAND_PACKAGE_MAX_NAME_BYTES,
  BRAND_PACKAGE_MAX_TEXT_BYTES,
  BRAND_PACKAGE_MEDIA_TYPES,
  BRAND_PACKAGE_SCHEMA_ID,
  BRAND_PACKAGE_SCHEMA_VERSION,
  computeBrandPackageDigest,
  parseBrandPackageToml,
  serializeBrandPackageToml,
  type BrandPackageCompanion,
  type BrandPackageCompanionPurpose,
  type BrandPackageInventoryItem,
  type BrandPackageMediaType,
  type BrandPackageModel,
  type BrandPackageNpm,
} from "./brand/brand-package.js";
export {
  BRAND_BUNDLE_MANIFEST_DIGEST_BASIS,
  BRAND_BUNDLE_MANIFEST_FILENAME,
  BRAND_BUNDLE_MANIFEST_SCHEMA,
  BRAND_BUNDLE_MANIFEST_SCHEMA_VERSION,
  BRAND_MANIFEST_MAX_BYTES,
  BRAND_MANIFEST_MAX_COMPANIONS,
  BRAND_MANIFEST_MAX_INVENTORY,
  BRAND_MANIFEST_MAX_PROFILES,
  computeBrandBundleManifestDigest,
  parseBrandBundleManifest,
  serializeBrandBundleManifest,
  type BrandBundleManifest,
  type BrandBundleManifestCompanion,
  type BrandBundleManifestInventoryItem,
  type BrandBundleManifestProfile,
  type BrandBundleManifestQaBaseline,
} from "./brand/brand-bundle-manifest.js";
export {
  BRAND_BUNDLE_LIMITS,
  bundleBrandProject,
  disposeBrandBundlePlan,
  executeBrandBundle,
  planBrandBundle,
  type BrandBundleEntryDto,
  type BrandBundleOptions,
  type BrandBundlePlan,
  type BrandBundleResult,
  type BrandBundleTransactionHooks,
  type BrandTargetSnapshot,
} from "./brand/brand-bundle.js";
export {
  BRAND_IMPORT_LIMITS,
  disposeBrandImportPlan,
  executeBrandImport,
  importBrandProject,
  planBrandImport,
  type BrandImportCompanionSummary,
  type BrandImportFileSummary,
  type BrandImportOptions,
  type BrandImportPlan,
} from "./brand/brand-import.js";
export {
  type BrandListInventory,
  type BrandListInventoryBinding,
  type BrandListInventoryDomain,
  type BrandListInventoryFamily,
  type BrandListInventoryVariant,
} from "./list.js";
export {
  type BrandCheckDomain,
  type BrandCheckResult,
  type BrandCheckQaStatus,
} from "./check.js";
export {
  BRAND_TOKENS_DIGEST_BASIS,
  BRAND_TOKENS_MAX_BYTES,
  BRAND_TOKENS_MAX_COUNT,
  BRAND_TOKENS_MAX_DEPTH,
  BRAND_TOKENS_MAX_REFERENCES,
  BRAND_TOKENS_SCHEMA_ID,
  BRAND_TOKENS_SCHEMA_VERSION,
  computeBrandTokensDigest,
  canonicalUsedTokenValue,
  findUnusedTokens,
  parseBrandTokensToml,
  serializeBrandTokensToml,
  toBrandTokensCanonicalDto,
  type BrandColorToken,
  type BrandDimensionToken,
  type BrandGradientStop,
  type BrandGradientToken,
  type BrandOpacityToken,
  type BrandTokensModel,
} from "./brand/tokens.js";
export {
  DERIVED_RECEIPT_DIGEST_BASIS,
  DERIVED_RECEIPT_MAX_BYTES,
  DERIVED_RECEIPT_MAX_COUNT,
  DERIVED_RECEIPT_SCHEMA_ID,
  DERIVED_RECEIPT_SCHEMA_VERSION,
  computeDerivedReceiptDigest,
  createBrandDerivedReceipt,
  parseBrandDerivedReceipt,
  serializeBrandDerivedReceipt,
  toDerivedReceiptPreimageDto,
  type BrandDerivedReceipt,
  type DerivedReceiptAccessibilityResult,
  type DerivedReceiptPayload,
  type DerivedReceiptResourceCounts,
  type DerivedReceiptSourceRecord,
  type DerivedReceiptUsedToken,
} from "./brand/derived-receipt.js";
export {
  BRAND_RECIPES_DIGEST_BASIS,
  BRAND_RECIPE_DIGEST_BASIS,
  BRAND_RECIPE_OPERATIONS_DIGEST_BASIS,
  BRAND_RECIPES_MAX_BYTES,
  BRAND_RECIPES_MAX_DERIVED_TARGETS,
  BRAND_RECIPES_MAX_GRAPH_DEPTH,
  BRAND_RECIPES_MAX_OPERATIONS_PER_RECIPE,
  BRAND_RECIPES_MAX_RECIPES,
  BRAND_RECIPES_MAX_TOTAL_APPLICATIONS,
  BRAND_RECIPES_MIN_OPERATIONS_PER_RECIPE,
  BRAND_RECIPES_SCHEMA_ID,
  BRAND_RECIPES_SCHEMA_VERSION,
  buildRecipeGraph,
  computeBrandRecipesDigest,
  computeBrandRecipeDefinitionDigest,
  computeBrandRecipeOperationsDigest,
  parseBrandRecipesToml,
  serializeBrandRecipesToml,
  toBrandRecipesCanonicalDto,
  toBrandRecipeCanonicalDto,
  toBrandRecipeOperationsCanonicalDto,
  type BackgroundPlateOperation,
  type BrandRecipe,
  type BrandRecipeOperation,
  type BrandRecipesModel,
  type CopyAccessibilityOperation,
  type CopyMetadataOperation,
  type MonochromeOperation,
  type RecipeGraph,
  type RecipeGraphNode,
  type RemoveGroupOperation,
  type ReplacePaintOperation,
  type ResizeCanvasOperation,
  type RetainGroupsOperation,
} from "./brand/recipes.js";
export {
  applyRecipeOperations,
  deriveBrandProject,
  disposeBrandDerivationPlan,
  executeBrandDerivationPlan,
  planBrandDerivation,
  type BrandDeriveOperationSummary,
  type BrandDeriveOptions,
  type BrandDerivePlan,
  type BrandDeriveResult,
  type BrandDeriveTargetSummary,
} from "./brand/derive.js";
export {
  BRAND_DERIVED_RECEIPT_DIR,
  BRAND_BASELINE_DIR,
  BRAND_BASELINE_MAX_AGGREGATE_BYTES,
  BRAND_BASELINE_MAX_FILE_BYTES,
  BRAND_BASELINE_MAX_FILES,
  brandBaselinePath,
  isBrandBaselinePath,
  parseBrandBaselinePath,
  DERIVED_RECEIPT_SUFFIX,
  derivedReceiptPath,
  derivedReceiptTargetId,
  isDerivedReceiptPath,
} from "./brand/brand-files.js";
export {
  BRAND_QA_SCHEMA_ID,
  BRAND_QA_SCHEMA_VERSION,
  BRAND_QA_DIGEST_BASIS,
  BRAND_QA_MAX_BYTES,
  BRAND_QA_MAX_PROFILES,
  BRAND_QA_MAX_CASES,
  BRAND_QA_MAX_VISUAL_CASES,
  BRAND_QA_MAX_TARGETS_PER_CASE,
  BRAND_QA_MAX_SIZES,
  BRAND_QA_MAX_BACKGROUNDS,
  BRAND_QA_MAX_EVALUATIONS_PER_PROFILE,
  BRAND_QA_MAX_DIMENSION,
  BRAND_QA_MAX_PIXELS_PER_EVALUATION,
  BRAND_QA_MAX_AGGREGATE_RGBA_BYTES,
  BRAND_QA_MAX_RESULT_BYTES,
  BRAND_QA_FORMATS,
  BRAND_QA_SEMANTIC_KINDS,
  BRAND_QA_VISUAL_KINDS,
  type BrandQaFormat,
  type BrandQaRendererPolicy,
  type BrandQaBackground,
  type BrandQaSize,
  type BrandQaSemanticKind,
  type BrandQaVisualKind,
  type BrandQaProfile,
  type BrandQaTargetSelector,
  type BrandQaInventoryCase,
  type BrandQaAccessibilityCase,
  type BrandQaPaletteCase,
  type BrandQaExternalReferenceCase,
  type BrandQaEmbeddedContentCase,
  type BrandQaRecipeCase,
  type BrandQaCanvasCase,
  type BrandQaPixelBoundsCase,
  type BrandQaTransparentBoundsCase,
  type BrandQaClippingCase,
  type BrandQaVisiblePaddingCase,
  type BrandQaSmallSizeVisibilityCase,
  type BrandQaBaselineCase,
  type BrandQaSemanticCase,
  type BrandQaVisualCase,
  type BrandQaCase,
  type BrandQaModel,
  isBrandQaVisualCase,
  parseBrandQaToml,
  toBrandQaCanonicalDto,
  serializeBrandQaToml,
  computeBrandQaDigest,
} from "./brand/qa-schema.js";
export {
  BRAND_QA_RENDER_CONFIGURATION,
  type BrandQaRendererDescriptor,
  type BrandQaResolvedRenderConfiguration,
  type BrandQaRenderInput,
  type BrandQaDecodeInput,
  type BrandQaNormalizedRaster,
  type BrandQaRendererCapability,
  type BrandQaBounds,
  type BrandQaRasterMeasurements,
  type BrandQaRasterDifference,
  type BrandQaRasterBudget,
  validateBrandQaRendererDescriptor,
  parseBrandQaBackgroundRgba,
  validateBrandQaNormalizedRaster,
  renderBrandQaRaster,
  decodeBrandQaBaseline,
  measureBrandQaRaster,
  countBrandQaForbiddenEdgePixels,
  compareBrandQaRasters,
} from "./brand/qa-capability.js";
export {
  BRAND_QA_RESULT_SCHEMA,
  BRAND_QA_RESULT_SCHEMA_VERSION,
  BRAND_QA_RESULT_DIGEST_BASIS,
  type BrandQaStatus,
  type BrandQaExitCode,
  type BrandQaJsonValue,
  type BrandQaTargetIdentity,
  type BrandQaDiagnostic,
  type BrandQaEvaluationResult,
  type BrandQaCaseResult,
  type BrandQaCounts,
  type BrandQaResult,
  type CreateBrandQaResultInput,
  computeBrandQaExitCode,
  computeBrandQaResultDigest,
  createBrandQaResult,
  serializeBrandQaResult,
  projectBrandQaResultMarkdown,
  projectBrandQaResultHtml,
} from "./brand/qa-report.js";
export {
  type BrandQaExecutionContext,
  runBrandQaProfile,
  runBrandQaSemanticProfile,
  runLoadedBrandQaProfile,
} from "./brand/qa-semantic.js";
export {
  type BrandQaBaselineUpdateOptions,
  type BrandQaBaselineCreate,
  type BrandQaBaselineUpdatePlan,
  type BrandQaBaselineUpdateResult,
  planBrandQaBaselineUpdate,
  executeBrandQaBaselineUpdatePlan,
  disposeBrandQaBaselineUpdatePlan,
} from "./brand/qa-baseline.js";
export {
  BRAND_DIFF_SCHEMA,
  BRAND_DIFF_SCHEMA_VERSION,
  BRAND_DIFF_DIGEST_BASIS,
  type BrandDiffChange,
  type BrandDiffSnapshot,
  type BrandDiffResult,
  createBrandDiffSnapshot,
  createLoadedProjectBrandDiffSnapshot,
  computeBrandDiffResultDigest,
  compareBrandSnapshots,
  serializeBrandDiff,
  projectBrandDiffMarkdown,
  projectBrandDiffHtml,
} from "./brand/brand-diff.js";
export {
  BRAND_VISUAL_DIFF_SCHEMA,
  BRAND_VISUAL_DIFF_SCHEMA_VERSION,
  BRAND_VISUAL_DIFF_DIGEST_BASIS,
  type BrandVisualDiffInputIdentity,
  type BrandVisualDiffOptions,
  type BrandVisualDiffResult,
  computeBrandVisualDiffResultDigest,
  compareBrandVisuals,
  serializeBrandVisualDiff,
} from "./brand/visual-diff.js";
export {
  CONSUMER_PROFILES_SCHEMA_ID,
  CONSUMER_PROFILES_SCHEMA_VERSION,
  CONSUMER_PROFILES_MAX_BYTES,
  CONSUMER_PROFILES_DIGEST_BASIS,
  CONSUMER_PROFILE_DIGEST_BASIS,
  type ConsumerProfileRequirement,
  type ConsumerProfileFilenamePolicy,
  type ConsumerProfileParameter,
  type ConsumerProfileCondition,
  type ConsumerProfileOutputRule,
  type ConsumerProfile,
  type ConsumerProfilesModel,
  parseConsumerProfilesToml,
  serializeConsumerProfilesToml,
  computeConsumerProfilesDomainDigest,
  computeConsumerProfileDigest,
  isBrandVersionCompatible,
} from "./brand/consumer-profile.js";
export {
  CONSUMER_LOCK_SCHEMA,
  CONSUMER_LOCK_SCHEMA_VERSION,
  CONSUMER_LOCK_MAX_BYTES,
  CONSUMER_LOCK_DIGEST_BASIS,
  CONSUMER_PROJECT_DIGEST_BASIS,
  type ConsumerLockSource,
  type ConsumerLockSelectedProfile,
  type ConsumerLockAssetMapping,
  type ConsumerLockCompanionMapping,
  type ConsumerLockInstalledMapping,
  type ConsumerLockPackage,
  type ConsumerBrandLockWithoutDigest,
  type ConsumerBrandLock,
  computeConsumerLockDigest,
  computeConsumerProjectDigest,
  createConsumerBrandLock,
  parseConsumerBrandLock,
  serializeConsumerBrandLock,
  mergeConsumerLockPackage,
} from "./brand/consumer-lock.js";
export {
  type ConsumerSourceOptions,
  type VerifiedConsumerPackage,
  type VerifiedConsumerSources,
  verifyConsumerSources,
  revalidateConsumerSources,
  disposeConsumerSources,
} from "./brand/consumer-source.js";
export {
  type ConsumerOperation,
  type ConsumerSelectionOptions,
  type ConsumerPlanOptions,
  type ConsumerPlanOutputSummary,
  type ConsumerPlanSummary,
  type ConsumerInstallPlan,
  type ConsumerSyncPlan,
  type ConsumerAdoptionPlan,
  type ConsumerStateStatus,
  type ConsumerStateMapping,
  type ConsumerStateInspection,
  planConsumerInstall,
  planConsumerSync,
  planConsumerAdoption,
  disposeConsumerPlan,
  inspectConsumerState,
} from "./brand/consumer-plan.js";
export {
  type ConsumerTransactionHooks,
  type ConsumerInstallResult,
  executeConsumerInstallPlan,
  executeConsumerSyncPlan,
  executeConsumerAdoptionPlan,
} from "./brand/consumer-install.js";
export {
  BRAND_EXPORTS_SCHEMA_ID,
  BRAND_EXPORTS_SCHEMA_VERSION,
  BRAND_EXPORTS_MAX_BYTES,
  BRAND_EXPORTS_DIGEST_BASIS,
  BRAND_EXPORT_PROFILE_DIGEST_BASIS,
  BRAND_EXPORT_OUTPUT_DIGEST_BASIS,
  parseBrandExportsToml,
  serializeBrandExportsToml,
  computeBrandExportsDomainDigest,
  computeRawBrandExportsFileDigest,
  computeBrandExportProfileDigest,
  computeBrandExportOutputDigest,
  validateBrandExportSemantics,
  type BrandExportsModel,
  type BrandExportProfile,
  type BrandExportOutput,
} from "./brand/export-profile.js";
export {
  RASTER_RECEIPT_SCHEMA_ID,
  RASTER_RECEIPT_SCHEMA_VERSION,
  RASTER_RECEIPT_DIGEST_BASIS,
  createRasterReceipt,
  parseRasterReceipt,
  serializeRasterReceipt,
  rasterReceiptPath,
  computeRasterReceiptDigest,
  type RasterReceipt,
  type RasterAdapterDescriptor,
} from "./brand/raster-receipt.js";
export {
  RASTER_COMPANION_PACKAGE,
  RASTER_ADAPTER_ID,
  decodeStrictPng,
  assertRasterSvgIsSelfContained,
  loadRasterCapability,
  type RasterCapabilityStatus,
  type RasterAdapterCapability,
  type RasterRenderRequest,
} from "./brand/raster-capability.js";
export {
  inspectRasterExportState,
  planRasterExport,
  executeRasterExportPlan,
  exportRasterProject,
  disposeRasterExportPlan,
  type RasterOwnershipState,
  type RasterStateInspection,
  type RasterExportPlan,
  type RasterExportPlanOptions,
  type RasterExportResult,
} from "./brand/export-plan.js";
